version: "3"

services:
  neji:
    build:
      context: ./neji
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./neji:/neji
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=andes.ebanx.local
