version: "3"

services:
  neji:
    build:
      context: ./neji
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./neji:/neji
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=hyuuga.neji.local
    depends_on:
      - byakugan
      - konoha

  konoha:
    image: mongo:latest
    ports:
      - 27017:27017

  hanabi:
    build:
      context: ./hanabi
    command: node index.js
    volumes:
      - ./hanabi:/hanabi
    environment:
      - VIRTUAL_HOST=hyuuga.hinabi.local
    depends_on:
      - byakugan

  byakugan:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
     - RABBITMQ_ERLANG_COOKIE=coockie
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
     - VIRTUAL_HOST=hyuuga.byakugan.local
