version: "3"

services:
  neji:
    build:
      context: ./neji
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./neji:/neji
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=hyuuga.neji.local

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    environment:
      - VIRTUAL_HOST=hyuuga.database.local
